name: Second Workflow
on: 
  push: # runs the workflow when a push event on main branch will trigger the workflow
    branches:
      - 'main'
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Starting
        run: echo "Will set node 18" 
      - name: Setting up node    
        uses: actions/setup-node@v3 # for action you use "uses: action_name"
        with: 
          node-version: 18 # can configure the action
      - name: Ending
        run: echo "Bye bye"
  build:
    needs: setup # it will start after setup job will finish with success. can depend on multiple jobs using an array [ job1, job2, job3 ] 
    runs-on: ubuntu-latest
    steps:
      - name: Start Build
        run: echo "Starting build"
      - name: End Build
        run: echo "Ending Build"
